# docker-compose -f webstore-stack.yml up

# Use root/example as user/password credentials
version: '1.0'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  WebStore:
    image: cgfootman/Webstore:latest
    restart: always
    ports:
      - 80:80